{% set name = "obspyck" %}
{% set version = "0.6.1" %}
{% set sha256 = "0c639d9a3029db757c506e3a662cc2644733054595ce1a1accfa6c7feeb10bd6" %}
 
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [not py27 or win]

requirements:
  build:
    - python 2.7*
    - setuptools
  run:
    - python 2.7*
    - obspy >=1.1.0
    - numpy
    - scipy
    - matplotlib
    - pyqt <5

test:
  imports:
    - obspyck
    - obspyck.obspyck
    - obspyck.util
    - obspyck.qt_designer
  commands:
    - obspyck -h

about:
  home: http://github.com/megies/obspyck
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE.txt
  summary: 'A GUI application for seismogram analysis'

  description: |
    ObsPyck is a GUI application that is intended to cover the tasks in a
    standard analysis workflow for seismic events in seismological observatory
    practice.
  dev_url: https://github.com/megies/obspyck

extra:
  recipe-maintainers:
    - megies
