{% set name = "obspyck" %}
{% set version = "0.8.1" %}
{% set sha256 = "e6864e355a12f54dac530d04d14fb93c93d070636cdd1ec6abda90d8e611d5d5" %}
 
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - obspyck = obspyck.obspyck:main

requirements:
  host:
    - python 3
    - setuptools
    - pip
  run:
    - python 3
    - obspy >=1.1.0
    - numpy
    - scipy
    - matplotlib
    - pyqt 5

test:
  imports:
    - obspyck
    - obspyck.obspyck
    - obspyck.util
    - obspyck.qt_designer
  commands:
    - obspyck -h

about:
  home: http://github.com/megies/obspyck
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: LICENSE.txt
  summary: 'A GUI application for seismogram analysis'

  description: |
    ObsPyck is a GUI application that is intended to cover the tasks in a
    standard analysis workflow for seismic events in seismological observatory
    practice.
  dev_url: https://github.com/megies/obspyck

extra:
  recipe-maintainers:
    - megies
