# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TxmXq9HPGkQFqH9IK7ZpSFWQCcm2smlpVObKGtKmVqu/wdjq9dR9W+8NDDARnY2UVL58kuPvczHfSBVx0t+ev3NkdCon2CaZLJnromw+TXvVB9MIEM/8o+mifFQIhuktH+VYPt9gnYFaHVGjt6ndRYgunk6y2AzuZHUTgAynJh1P/LdnVqNoNpe5W2Bkz9Mb5W401VfkyRD0FEUywewCy+/NgZjlAFvXbvx/IT+Le5B6j3IGzyEosR/tyR9ZxTgsWfWw7jobI4xZ9zNXAS+J/+pv6NT+G4E4RxpTTL7lde3DFpz0hdWO3s8hbBw79hWtGaj/Y1FXuTx1r+FJmB4wV/I86i0wh6Xfdyhy+JWhsYXVIIiSQoVkNbBKLui31xbyYRseJwyLc8RFnkz6/64WUC2YGyOszX4WeFJWSfWGiXZtqRkltMO0+52gbJbxAJXC0oG2iICPJyOssNBSysfBIxJOzA6j8Po4rRSizgtVrx3UKXtQBOw+NQi6aIMrsvE/R4/AeasH4YQH6ozp5gkIRAjkGE94ucedjTIx5WNRBHK6kHcc6tPtfU53mZJ5kw0c3t3bHlLfPlM4JyiH+KN9cvA8d+bDdwrHwmzP+Ik3ns05EA1cvGAsGjF0NGEU9ZXKHCDgHg8yclkmozUSCkHxiyI9WpXYCYZqqqRZEee2KfY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
