appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TxmXq9HPGkQFqH9IK7ZpSFWQCcm2smlpVObKGtKmVqu/wdjq9dR9W+8NDDARnY2UVL58kuPvczHfSBVx0t+ev3NkdCon2CaZLJnromw+TXvVB9MIEM/8o+mifFQIhuktH+VYPt9gnYFaHVGjt6ndRYgunk6y2AzuZHUTgAynJh1P/LdnVqNoNpe5W2Bkz9Mb5W401VfkyRD0FEUywewCy+/NgZjlAFvXbvx/IT+Le5B6j3IGzyEosR/tyR9ZxTgsWfWw7jobI4xZ9zNXAS+J/+pv6NT+G4E4RxpTTL7lde3DFpz0hdWO3s8hbBw79hWtGaj/Y1FXuTx1r+FJmB4wV/I86i0wh6Xfdyhy+JWhsYXVIIiSQoVkNbBKLui31xbyYRseJwyLc8RFnkz6/64WUC2YGyOszX4WeFJWSfWGiXZtqRkltMO0+52gbJbxAJXC0oG2iICPJyOssNBSysfBIxJOzA6j8Po4rRSizgtVrx3UKXtQBOw+NQi6aIMrsvE/R4/AeasH4YQH6ozp5gkIRAjkGE94ucedjTIx5WNRBHK6kHcc6tPtfU53mZJ5kw0c3t3bHlLfPlM4JyiH+KN9cvA8d+bDdwrHwmzP+Ik3ns05EA1cvGAsGjF0NGEU9ZXKHCDgHg8yclkmozUSCkHxiyI9WpXYCYZqqqRZEee2KfY=}
conda_forge_output_validation: true
