travis:
  secure:
    BINSTAR_TOKEN: YqSEUqP6gA55GbTWm5NtVRdvOz/HtumamMk7Oke5AG5SzIwP4NkuVujPWEGG3zK3kFUJmEA0gHfzWryzx0ytzpxxx6JhCi21xACp5n7tq2T6ozXsgldbcsSJZo2lkTroquk8EApJw6B4/sPBdxsDUGftrALFMV1Ccvju4/bvJOmo77ARSyopQmf4jmAQ9Ek2r0SXN1KJC1c8zR3dqJoR6Grft4m4/0UxcP8z3r+ASVT5ETDCXWvwvjapmJANbJbu8KFkJROru+xPWERZFWRHJV4hU/th3WhcrZl+N5QjXEj7KoOplODcElGpOlpY4E6BU/aUzs8tRz/McRG5GJvE044DBwCAshFUR3tIL6ivxS6Yv36YwR1VCDr6G94KaDr8GLHihJEnTVEYaC/rxxUNUWLhEgpMC6mmId2KoQ7Rvk4GnboTyo+8Gv1DBmWhBF6m0KmbP5TE0n5aHunsDWr8cYrVdvSoVaUlbBHTjguVRqIYc+R9Ky60F0YHDQlyWFrwvMZjKgnvE+PoMJB/DPsUOXWAVP5CVYeUFZAAnvA93IDPTxdMcMAVWSoliwA3eVJhYzhMISNrUnoWuNO7WWdoeQOI36xbPfHW/0y/GXuLyEo9RZLxpGQA1pCvpLYEoHC5pxeVIetOoz4LXmj+9Pxa3k+UCwLhAZxXPmRY3RyIl9c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
